"""Human-readable explanations for each detected attack type."""

EXPLANATIONS = {
    "SQL Injection":     "This payload attempts to manipulate database queries using SQL syntax, potentially exposing or destroying data.",
    "XSS":              "This payload injects malicious JavaScript that would execute in the victim's browser, enabling session theft or defacement.",
    "SSRF":             "This payload attempts to make the server issue requests to internal/private resources, bypassing firewall restrictions.",
    "Path Traversal":   "This payload navigates outside the web root using '../' sequences to read sensitive system files.",
    "Command Injection":"This payload attempts to execute arbitrary OS commands on the server via shell metacharacters.",
    "WAF_Bypass":       "This payload uses obfuscation or encoding tricks specifically designed to evade WAF pattern matching.",
    "Scanner":          "This request was generated by an automated scanning tool (sqlmap, nmap, masscan, etc.).",
    "AI_Anomaly":       "This request deviates significantly from normal traffic patterns — flagged by the Isolation Forest anomaly model.",
    "Adaptive_Rule":    "This request matches an automatically generated rule derived from a previous attack.",
    "Learned_Attack":   "This pattern was memorised from a previously confirmed attack and matched again.",
}


def explain_attack(payload: str, attack_type: str) -> str:
    return EXPLANATIONS.get(attack_type, "Unusual or unknown malicious behaviour detected in this request.")
